/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'

export const PickupModel = (props) => {
  const { nodes, materials } = useGLTF("/assets/gltf/diamond_teamBlue.gltf.glb");
  const pickupRef = useRef();
  const [up, setUp]= useState(true);
  useFrame(()=>{
    if(pickupRef.current) pickupRef.current.rotation.y += 0.01
  })
  return (
    <group {...props} visible={props.render} ref={pickupRef} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond_teamBlue.geometry}
        material={materials.Blue}
      />
    </group>
  );
}

useGLTF.preload("/assets/gltf/diamond_teamBlue.gltf.glb");