/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const PickupModel = (props) => {
  const { nodes, materials } = useGLTF("/assets/gltf/diamond_teamBlue.gltf.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond_teamBlue.geometry}
        material={materials.Blue}
      />
    </group>
  );
}

useGLTF.preload("/assets/gltf/diamond_teamBlue.gltf.glb");