/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/**default scale is [2, 1.5, 2]*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export const TileModel = (props) => {
  const { nodes, materials } = useGLTF("/assets/gltf/tileMedium_forest.gltf.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube1615.geometry}
      >
        <meshBasicMaterial color={'#45b39d'}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube1615_1.geometry}
      >
        <meshBasicMaterial color={'#725038'}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/assets/gltf/tileMedium_forest.gltf.glb");
